call C:\sandbox-utils\app-script\msys2-favorite-binary-download.bat
call C:\sandbox-utils\app-script\7zip-download.bat
call C:\sandbox-utils\app-script\npp-download.bat
call C:\sandbox-utils\app-script\chrome-download.bat
call C:\sandbox-utils\app-script\git-download.bat
call C:\sandbox-utils\app-script\sam-git-utils-download.bat
call C:\sandbox-utils\app-script\python-download.bat
call C:\sandbox-utils\app-script\vscode-download.bat
call C:\sandbox-utils\app-script\bginfo-download.bat
call C:\sandbox-utils\app-script\jq-download.bat
call C:\sandbox-utils\app-script\setdefaultbrowser-download.bat
call C:\sandbox-utils\app-script\windows-termina-download.bat